import type {
  Building,
  ImprovementType,
  SpaceshipPart,
  Technology,
  TerrainType,
  Yield,
} from "./types";

export const terrainLabels: Record<TerrainType, string> = {
  plains: "平原",
  forest: "森林",
  hill: "丘陵",
  mountain: "山岳",
  river: "河川",
  sea: "海",
  desert: "砂漠",
};

export const terrainEmoji: Record<TerrainType, string> = {
  plains: "🌾",
  forest: "🌲",
  hill: "⛰️",
  mountain: "🏔️",
  river: "🏞️",
  sea: "🌊",
  desert: "🏜️",
};

export const terrainYields: Record<TerrainType, Yield> = {
  plains: { food: 2, production: 0, science: 0, culture: 0 },
  forest: { food: 1, production: 1, science: 0, culture: 0 },
  hill: { food: 0, production: 2, science: 0, culture: 0 },
  mountain: { food: 0, production: 1, science: 1, culture: 0 },
  river: { food: 2, production: 0, science: 0, culture: 1 },
  sea: { food: 1, production: 0, science: 0, culture: 0 },
  desert: { food: 0, production: 0, science: 0, culture: 0 },
};

export const improvementLabels: Record<ImprovementType, string> = {
  farm: "農場",
  mine: "鉱山",
  lumber: "伐採地",
};

export const improvementYields: Record<ImprovementType, Yield> = {
  farm: { food: 1, production: 0, science: 0, culture: 0 },
  mine: { food: 0, production: 1, science: 0, culture: 0 },
  lumber: { food: 0, production: 1, science: 0, culture: 0 },
};

export const eraLabels = {
  ancient: "古代",
  agricultural: "農耕時代",
  kingdom: "王国時代",
  industrial: "産業時代",
  modern: "現代",
  space: "宇宙時代",
} as const;

export const technologies: Technology[] = [
  {
    id: "agriculture",
    name: "農業",
    cost: 20,
    prerequisites: [],
    unlocks: ["granary", "farm"],
    era: "ancient",
    researched: false,
  },
  {
    id: "mining",
    name: "採掘",
    cost: 25,
    prerequisites: [],
    unlocks: ["mine"],
    era: "ancient",
    researched: false,
  },
  {
    id: "writing",
    name: "文字",
    cost: 35,
    prerequisites: [],
    unlocks: ["library"],
    era: "ancient",
    researched: false,
  },
  {
    id: "irrigation",
    name: "灌漑",
    cost: 35,
    prerequisites: ["agriculture"],
    unlocks: ["foodBonus"],
    era: "ancient",
    researched: false,
  },
  {
    id: "metalworking",
    name: "金属加工",
    cost: 45,
    prerequisites: ["mining"],
    unlocks: ["workshop"],
    era: "ancient",
    researched: false,
  },
  {
    id: "law",
    name: "法律",
    cost: 50,
    prerequisites: ["writing"],
    unlocks: ["courthouse", "stabilityBonus"],
    era: "ancient",
    researched: false,
  },
  {
    id: "administration",
    name: "行政",
    cost: 70,
    prerequisites: ["law"],
    unlocks: ["cityLimitBonus"],
    era: "medieval",
    researched: false,
  },
  {
    id: "mathematics",
    name: "数学",
    cost: 75,
    prerequisites: ["writing"],
    unlocks: ["scienceBonus"],
    era: "medieval",
    researched: false,
  },
  {
    id: "engineering",
    name: "工学",
    cost: 80,
    prerequisites: ["metalworking", "mathematics"],
    unlocks: ["aqueduct", "productionBonus"],
    era: "medieval",
    researched: false,
  },
  {
    id: "education",
    name: "教育",
    cost: 95,
    prerequisites: ["administration", "mathematics"],
    unlocks: ["university"],
    era: "medieval",
    researched: false,
  },
  {
    id: "machinery",
    name: "機械",
    cost: 100,
    prerequisites: ["engineering"],
    unlocks: ["workshopBonus"],
    era: "renaissance",
    researched: false,
  },
  {
    id: "astronomy",
    name: "天文学",
    cost: 110,
    prerequisites: ["mathematics"],
    unlocks: ["observatory"],
    era: "renaissance",
    researched: false,
  },
  {
    id: "steamPower",
    name: "蒸気機関",
    cost: 130,
    prerequisites: ["machinery"],
    unlocks: ["steamFactory"],
    era: "industrial",
    researched: false,
  },
  {
    id: "scientificMethod",
    name: "科学的方法",
    cost: 130,
    prerequisites: ["education"],
    unlocks: ["scienceBoost"],
    era: "industrial",
    researched: false,
  },
  {
    id: "physics",
    name: "物理学",
    cost: 140,
    prerequisites: ["astronomy", "mathematics"],
    unlocks: ["physicsBonus"],
    era: "industrial",
    researched: false,
  },
  {
    id: "industrialization",
    name: "工業化",
    cost: 160,
    prerequisites: ["steamPower", "engineering"],
    unlocks: ["factory"],
    era: "industrial",
    researched: false,
  },
  {
    id: "chemistry",
    name: "化学",
    cost: 170,
    prerequisites: ["scientificMethod"],
    unlocks: ["chemicalPlant"],
    era: "industrial",
    researched: false,
  },
  {
    id: "electricity",
    name: "電気",
    cost: 190,
    prerequisites: ["industrialization", "physics"],
    unlocks: ["powerPlant", "laboratory"],
    era: "modern",
    researched: false,
  },
  {
    id: "flight",
    name: "航空",
    cost: 210,
    prerequisites: ["physics", "industrialization"],
    unlocks: ["airfield"],
    era: "modern",
    researched: false,
  },
  {
    id: "electronics",
    name: "電子工学",
    cost: 230,
    prerequisites: ["electricity"],
    unlocks: ["communicationCenter"],
    era: "modern",
    researched: false,
  },
  {
    id: "materialsScience",
    name: "材料工学",
    cost: 240,
    prerequisites: ["chemistry", "industrialization"],
    unlocks: ["advancedMaterials"],
    era: "modern",
    researched: false,
  },
  {
    id: "computers",
    name: "コンピュータ",
    cost: 260,
    prerequisites: ["electronics"],
    unlocks: ["controlSystem"],
    era: "modern",
    researched: false,
  },
  {
    id: "rocketry",
    name: "ロケット工学",
    cost: 280,
    prerequisites: ["flight", "chemistry", "electricity"],
    unlocks: ["spaceport"],
    era: "space",
    researched: false,
  },
  {
    id: "spacecraftConstruction",
    name: "宇宙船建造",
    cost: 320,
    prerequisites: ["rocketry", "materialsScience", "computers"],
    unlocks: ["spaceshipParts"],
    era: "space",
    researched: false,
  },
];

export const buildings: Building[] = [
  {
    id: "granary",
    name: "穀倉",
    cost: 30,
    requiredTech: "agriculture",
    effect: { food: 2 },
    description: "都市の食料産出 +2",
  },
  {
    id: "monument",
    name: "記念碑",
    cost: 25,
    requiredTech: null,
    effect: { culture: 2 },
    description: "文化 +2",
  },
  {
    id: "library",
    name: "図書館",
    cost: 40,
    requiredTech: "writing",
    effect: { science: 3 },
    description: "知識 +3",
  },
  {
    id: "courthouse",
    name: "裁判所",
    cost: 50,
    requiredTech: "law",
    effect: { stability: 10 },
    description: "安定度 +10",
  },
  {
    id: "workshop",
    name: "作業場",
    cost: 55,
    requiredTech: "metalworking",
    effect: { production: 3 },
    description: "生産力 +3",
  },
  {
    id: "aqueduct",
    name: "水道",
    cost: 60,
    requiredTech: "engineering",
    effect: { food: 2, stability: 3 },
    description: "食料 +2、安定度 +3",
  },
  {
    id: "university",
    name: "大学",
    cost: 75,
    requiredTech: "education",
    effect: { science: 5 },
    description: "知識 +5",
  },
  {
    id: "factory",
    name: "工場",
    cost: 90,
    requiredTech: "industrialization",
    effect: { production: 8, stability: -5 },
    description: "生産力 +8、安定度 -5",
  },
  {
    id: "laboratory",
    name: "研究所",
    cost: 110,
    requiredTech: "electricity",
    effect: { science: 8 },
    description: "知識 +8",
  },
  {
    id: "powerPlant",
    name: "発電所",
    cost: 120,
    requiredTech: "electricity",
    effect: { production: 6, science: 2, stability: -3 },
    description: "生産力 +6、知識 +2、安定度 -3",
  },
  {
    id: "spaceport",
    name: "宇宙船発射場",
    cost: 160,
    requiredTech: "rocketry",
    effect: {},
    description: "宇宙船パーツを生産可能にする",
  },
];

export const spaceshipParts: SpaceshipPart[] = [
  {
    id: "engine",
    name: "エンジン",
    cost: 150,
    requiredTechs: ["rocketry", "materialsScience"],
    requiredBuilding: "spaceport",
  },
  {
    id: "habitat",
    name: "居住区",
    cost: 150,
    requiredTechs: ["materialsScience"],
    requiredBuilding: "spaceport",
  },
  {
    id: "controlSystem",
    name: "管制システム",
    cost: 150,
    requiredTechs: ["computers"],
    requiredBuilding: "spaceport",
  },
];

export const technologyEraLabels: Record<string, string> = {
  ancient: "古代",
  medieval: "中世",
  renaissance: "近世",
  industrial: "産業時代",
  modern: "現代",
  space: "宇宙時代",
};
